# Generated by Django 4.2.6 on 2023-11-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=50)),
                ("remote", models.BooleanField(default=False)),
                ("salary", models.IntegerField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
