# Generated by Django 4.2.6 on 2023-11-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_alter_job_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="available",
            field=models.BooleanField(default=True),
        ),
    ]
