# Generated by Django 4.2.6 on 2023-11-01 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0003_job_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="company_logo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="job",
            name="company_name",
            field=models.CharField(default="Google", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="company_website",
            field=models.URLField(default="https://google.com"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
