# Generated by Django 4.2.6 on 2023-11-06 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_job_company_logo_job_company_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SponsoredJobPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_until", models.DateTimeField()),
                ("stripe_payment_intent", models.CharField(max_length=150)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sponsored_posts", to="jobs.job"
                    ),
                ),
            ],
        ),
    ]
