# Generated by Django 4.2.6 on 2023-11-06 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0006_job_sponsored"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sponsoredjobpost",
            old_name="stripe_payment_intent",
            new_name="stripe_payment_intent_id",
        ),
    ]
